### ISSUE TITLE
Nuget unable to install 1.6.0 in .Net Core 3.1 application

### ISSUE THREAD

**Issue by Abrissirba** [philipdaubmeier/GraphIoT#6]
I tried to upgrade NetatmoWebClient to 1.6.0 in my .Net Core 3.1 application and got the following error message. I also tested to create an empty project and install 1.6.0 but got the same error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package PhilipDaubmeier.NetatmoClient 1.6.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package PhilipDaubmeier.NetatmoClient 1.6.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	NetatmoTest	C:\Users\Mackan\source\repos\NetatmoTest\NetatmoTest\NetatmoTest.csproj	1	
```

**Comment by philipdaubmeier** [comment]
Hmm, I thought if I change the target to netstandard2.1 it will still support netcore3.1 and also others (like Mono and Xamarin). Perhaps I have to add it explicitly in the nuspec?

I'll have a closer look at that

**Comment by philipdaubmeier** [comment]
Ok, that was more complicated than I thought it would be. I could immediatelly reproduce it when creating a netcore3.1 console app, while working fine when referenced from netcore3.1 projects in the GraphIoT solution - meaning it has something to do with the compiled and packaged assembly in the nuget package.

I then figured I extend the project to multi target both netstandard2.1 and netcore3.1. This in turn does no longer work together with `nuget pack` then, but requires `dotnet pack` or `msbuild -t:pack`, both of which ignored my nuspec file. I could fix this also by referencing the nuspec in the project file - which then broke the variables in the nuspec file 😑. I found a github thread and working example of a prepoluation build step - et voilà!

Should be fixed with [78625e8](https://github.com/philipdaubmeier/GraphIoT/commit/78625e854329f62314869a42a57bfffdbd19dfee) now.

I just published a new version 1.6.1 that should work again. Thanks for reporting!

**Comment by Abrissirba** [comment]
That sounds very familiar to what I had to do at work a while ago. Remeber the frustration with nuget pack vs dotnet pack... What github thread did you find?

**Comment by philipdaubmeier** [comment]
This one here: [dotnetsdk/#5525](https://github.com/dotnet/sdk/issues/5525)

**Comment by Abrissirba** [comment]
Thanks and thanks for fixing it so quick!
